== picketlink-forge-addon
:idprefix: id_ 

The picketlink-forge-addon enables security to your project by providing configuration options to quickly setup *Authentication*, 
*Authorization* and *Identity Management* to your project.

PicketLink is an umbrella project for Security and Identity Management for Java Applications and fully integrated with CDI:

- JavaEE Security
- Identity Management
- Support for Federation Protocols such as SAML, oAuth and OpenID.
- Social Authentication
- Token Management and Authentication
- Authorization based on Security Annotations and EL Expressions
- RESTFul and Mobile Security Features

More details on http://picketlink.org[picketlink.org]. 
        
=== Depends on

[options="header"]
|===
|Addon |Exported |Optional

|ui
|no
|no

|projects
|yes
|no

|parser-java
|yes
|no

|javaee
|yes
|no

|configuration
|yes
|no

|maven
|yes
|no

|org.jboss.forge.furnace.container:cdi
|no
|no

|===

== Building Sources and Forge Installation

If you want to use the latest changes for this addon, please clone the https://github.com/picketlink/picketlink-forge-addon/[PicketLink Forge Addon Repository] in GitHub.

        git clone https://github.com/picketlink/picketlink-forge-addon/
        
Once you've successfully cloned the repository, navigate to the newly created directory:

        cd picketlink-forge-addon
        
Make sure Forge is properly installed and configured in your environment. If so, you should be able to start Forge by typing

        forge
        
IMPORTANT: For more details about how to install Forge, follow the instructions https://github.com/forge/core/blob/master/README.asciidoc[here].
        
Once you're in Forge Shell perform a build as follows:

        build --notest clean install
        
After that, enter the *addon* module 

        cd addon
        
And finally install the addon into your Forge installation

        addon-build-and-install
        
If everything was fine, you should be able to see the following command in Forge Shell

        picketlink-setup

== Features

Configuration of PicketLink Maven Dependencies::
   This addon configures all the necessary PicketLink dependencies to your project's pom.xml. All PicketLink-related dependencies are managed
by the PicketLink Bill Of Materials(BOM) as well their respective versions.
Swtich between different PicketLink Versions::
   This addon provides a easy way to choose a specific PicketLink version. This is useful if you want to test a specific version, including
snapshots. By default, the latest final released version is configured.

+
Descriptors are handled by the https://github.com/shrinkwrap/descriptors[ShrinkWrap Descriptors] project. Read the Facets addon README to learn how to handle facets in Forge. Below is a table that lists each facet and its purpose.
+
[options="header,asciidoc"]
|===
|Facet|Behavior when installing in a project

|`CDIFacet`
|Adds the necessary CDI 1.x dependencies to the build descriptor. Adds a `META-INF/beans.xml` to your resources directory or to `WEB-INF/beans.xml` if in a Web project. The facet provides access to the `BeansDescriptor` object to allow manipulation of the `beans.xml` file in a fluent way.

|`EJBFacet`
|Adds the necessary EJB 3.x dependencies to the build descriptor. 

|`JAXWSFacet`
|Adds the necessary JAX-WS dependencies to the build descriptor. 

|`JMSFacet`
|Adds the necessary JMS 1.1 dependencies to the build descriptor. 

|`JSTLFacet`
|Adds the necessary JSTL dependencies to the build descriptor. 

|`JTAFacet`
|Adds the necessary JTA dependencies to the build descriptor. 

|`PersistenceFacet`
|Adds the necessary JPA 2.x dependencies to the build descriptor. Adds a `META-INF/persistence.xml` to your project. Provides access to the `PersistenceDescriptor` object to allow manipulation of the `persistence.xml` file in a fluent way. 

|`PersistenceMetaModelFacet`
|Adds the necessary configuration in the build descriptor to enable JPA 2.x meta-model generation. 

|`ServletFacet`
|Adds the necessary Servlet 3.x dependencies to the build descriptor. Adds a `WEB-INF/web.xml` to your project. Provides access to the `WebAppDescriptor` object to allow manipulation of the `web.xml` file in a fluent way. 

|===

JPA configuration :: 
 The javaee addon supports out-of-the-box configuration of the following JPA containers:
+
[options="header"]
|===
|Container|Tested Version(s) (Where applicable)

|JBoss WildFly
|-

|JBoss AS
|6.x / 7.x

|JBoss EAP
|6.x / 6.1.x

|Oracle WebLogic
|12c

|Oracle GlassFish
|3.x

|TomEE
|1.5.x

|SAP Lean Java Server
|-

|Non-JTA Container
|-

|Custom JDBC container
|-

|Custom JTA container
|-

|===
 
+
And the following JPA Providers:
+
- Hibernate 
- EclipseLink
- OpenJPA
- Infinispan

+
